import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Providers } from "./Providers";
import MobileHeader from "@/components/layout/MobileHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <MobileHeader />
        {children}
        </Providers>
      </body>
    </html>
  );
}
